version: '3.7'

services:
  resource:
    container_name: resource
    build:
      context: ./services/resource
      dockerfile: Dockerfile-dev
    volumes:
      - /sblog/services/resource/:/usr/src/app
    ports:
      - 5001:5000
    environment:
      - FLASK_APP=project/__init__.py
      - APP_SETTING=development
      - FLASK_ENV=development
      - DATABASE_DEV_URL=mysql+cymysql://root:jianxin123@users-db:3306/users_dev
      - DATABASE_TEST_URL=mysql+cymysql://root:jianxin123@users-db:3306/users_test
      - DATABASE_URL=mysql+cymysql://root:jianxin123@users-db:3306/users_prod
      - SECRET_KEY=my_precious
    depends_on:
      - users-db
    links:
      - users-db
  
  users-db:
    container_name: users-db
    build:
      context: ./services/resource/project/db
      dockerfile: Dockerfile
    ports:
      - 3308:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=jianxin123
    security_opt:
      - seccomp:unconfined

  nginx:
    container_name: nginx
    build:
      context: ./services/nginx
      dockerfile: Dockerfile-dev
    restart: always
    ports:
      - 80:80
    depends_on:
      - resource
      - client

  client:
    container_name: client
    build:
      context: ./services/client
      dockerfile: Dockerfile-dev
    volumes:
      - /sblog/services/client:/usr/src/app
    ports:
      - 3007:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_RESOURCES_SERVICE_URL=${REACT_APP_RESOURCES_SERVICE_URL}
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - resource

  swagger:
    container_name: swagger
    build:
      context: ./services/swagger
      dockerfile: Dockerfile-dev
    volumes:
      - '/sblog/services/swagger/swagger.json:/usr/share/nginx/html/swagger.json'
    ports:
      - '3008:8080'
    environment:
      - URL=/swagger.json
    depends_on:
      - resource
