FROM python:3.6.8

# install environment dependencies
RUN apt-get update -yqq \
    && apt-get install -yqq --no-install-recommends \
        netcat \
    && apt-get -q clean

# set work dir 
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# add requirements
COPY ./requirements.txt /usr/src/app/requirements.txt

# install requirements
RUN pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

# add entrypoint.sh
COPY ./entrypoint.sh /usr/src/app/entrypoint.sh

# add app 
COPY . /usr/src/app 

CMD ["./entrypoint.sh"]
# CMD ["python", "manager.py", "run", "-h", "0.0.0.0"]