FROM python:3.6.8

# install environment dependencies
# COPY ./sources.list /etc/apt/

RUN apt-get update -yqq \
    && apt-get install -yqq --no-install-recommends \
        netcat \
    && apt-get -q clean

# set work directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# add requirements
COPY ./requirements.txt /usr/src/app/requirements.txt

# install requirements
RUN pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

# add entrypoint.sh
COPY ./entrypoint-prod.sh /usr/src/app/entrypoint-prod.sh

# add app
COPY . /usr/src/app

# run server 
CMD ["./entrypoint-prod.sh"]
# CMD ["./entrypoint.sh"]