FROM node:10

# set work directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

# add /usr/src/app/node_modules/.bin to $PATH
ENV PATH /usr/src/app/node_modules/.bin:$PATH

# install dependencies
COPY ./package.json /usr/src/app/package.json
RUN npm config set registry https://registry.npm.taobao.org
RUN npm install --slient

# start app
CMD [ "npm", "start" ]